# Generated by Django 6.0.7 on 2026-08-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("googlehealth", "0003_googlehealthoauthstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlehealthconnection",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("disconnected", "Disconnected"),
                    ("revoked", "Revoked"),
                    ("unlinked", "Not linked to Google Health"),
                ],
                default="active",
                max_length=32,
            ),
        ),
    ]
