# Generated by Django 6.0.7 on 2026-09-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("googlehealth", "0004_alter_googlehealthconnection_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlehealthconnection",
            name="migrated_from",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apple_health", "Apple Health"),
                    ("fitbit", "Fitbit"),
                    ("garmin", "Garmin"),
                    ("google_health", "Google Health"),
                    ("health_connect", "Health Connect"),
                    ("oura", "Oura"),
                    ("strava", "Strava"),
                    ("whoop", "WHOOP"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
